apiVersion: v1
kind: ServiceAccount
metadata:
  name: delegate-pipeline
---
# Required to be able to hand out edit rights 
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: delegate-pipeline-edit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
  - kind: ServiceAccount
    name: delegate-pipeline
    namespace: tekton-pipelines
---
# Required to be able to hand out edit rights and create namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: delegate-pipeline-clusterrole
rules:
  - apiGroups: 
      - ""
    resources: 
      - "namespaces"
    verbs: 
      - "get"
      - "create"
  - apiGroups: 
      - "rbac.authorization.k8s.io"
    resources: 
      - "rolebindings"
    verbs: 
      - "get"
      - "create"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: delegate-pipeline-clusterbinding
subjects:
- kind: ServiceAccount
  name: delegate-pipeline
  namespace: tekton-pipelines
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: delegate-pipeline-clusterrole