apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/delegate-rbac.yaml
  - resources/delegate-pipeline.yaml
  - resources/create-namespace.yaml
  - resources/trigger-pipelines.yaml
  - resources/apply-tekton.yaml

configMapGenerator:
  - name: trigger-pipelines-scripts
    files:
      - pvc-template.yaml
      - pod-template.yaml
