apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/joyrex2001/tekline.git//library/pipelines/hello-world?ref=master
- https://github.com/joyrex2001/tekline.git//library/pipelines/hello-world-2?ref=master
